ORC/urls.py
from django.conf.urls import url
from . import views
from django.urls import path,re_path
from . import views as ORC_views
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from rest_framework.urlpatterns import format_suffix_patterns


app_name = 'ORC'
urlpatterns = [

    path('', views.about, name='about'),
    re_path(r'^home/$', views.about, name='home'),
    url('about/', views.about, name='about'),
    path('password_reset/', auth_views.PasswordResetView.as_view(success_url=reverse_lazy('ORC:password_reset_done')),
         {'email_template_name': 'registration/password_reset_email.html'}, name='password_reset'),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='registration/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='registration/password_reset_confirm.html'),name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='registration/password_reset_complete.html'),name='password_reset_complete'),
    path('password_change/done/',auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    url(r'^password/$', views.change_password, name='change_password'),
    url(r'^signup/$', ORC_views.signup, name='signup'),
    url('workorder_list/', views.workorder_list, name='workorder_list'),
    path('workorder/new/', views.workorder_new, name='workorder_new'),
    path('workorder/<int:pk>/edit/', views.workorder_edit, name='workorder_edit'),
    path('workorder/<int:pk>/delete/', views.workorder_delete, name='workorder_delete'),
    url('property_list/', views.property_list, name='property_list'),
    path('property/new/', views.property_new, name='property_new'),
    path('property/<int:pk>/edit/', views.property_edit, name='property_edit'),
    path('property/<int:pk>/delete/', views.property_delete, name='property_delete'),
    url('resident_list/', views.resident_list, name='resident_list'),
    path('resident/new/', views.resident_new, name='resident_new'),
    path('resident/<int:pk>/edit/', views.resident_edit, name='resident_edit'),
    path('resident/<int:pk>/delete/', views.resident_delete, name='resident_delete'),
    path('resident/<int:pk>/workorderview/', views.resident_workorderview, name='resident_workorderview'),
    url('maintenance_worker_list/', views.maintenance_worker_list, name='maintenance_worker_list'),
    path('maintenance_worker/new/', views.maintenance_worker_new, name='maintenance_worker_new'),
    path('maintenance_worker/<int:pk>/edit/', views.maintenance_worker_edit, name='maintenance_worker_edit'),
    path('maintenance_worker/<int:pk>/delete/', views.maintenance_worker_delete, name='maintenance_worker_delete'),
    url('equipment_list/', views.equipment_list, name='equipment_list'),
    path('equipment/new/', views.equipment_new, name='equipment_new'),
    path('equipment/<int:pk>/edit/', views.equipment_edit, name='equipment_edit'),
    path('equipment/<int:pk>/delete/', views.equipment_delete, name='equipment_delete'),
    url('orc_staff_list/', views.orc_staff_list, name='orc_staff_list'),
    path('orc_staff/new/', views.orc_staff_new, name='orc_staff_new'),
    path('orc_staff/<int:pk>/edit/', views.orc_staff_edit, name='orc_staff_edit'),
    path('orc_staff/<int:pk>/delete/', views.orc_staff_delete, name='orc_staff_delete'),
    path('maintenancework_list/', views.maintenancework_list, name='maintenancework_list'),
    path('maintenancework/new/', views.maintenancework_new, name='maintenancework_new'),
    path('maintenancework/<int:pk>/edit/', views.maintenancework_edit, name='maintenancework_edit'),
    path('maintenancework/<int:pk>/delete/', views.maintenancework_delete, name='maintenancework_delete'),
    path('maintenancework/<int:pk>/workerview/', views.maintenancework_workerview, name='maintenancework_workerview'),

    url(r'export/xls/$', views.export_workorders_excel, name='export_workorders_xls'),
    url(r'^workorders_json/', views.WorkorderList.as_view()),
    url(r'^residents_json/', views.ResidentList.as_view()),
]

urlpatterns = format_suffix_patterns(urlpatterns)

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path, re_path
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ORC.urls')),


    re_path(r'^accounts/login/$', LoginView.as_view(template_name='registration/login.html'), name="login"),
    re_path(r'^accounts/logout/$', LogoutView.as_view(), LogoutView.next_page, name="logout"),


# reset password urls
    path('password_reset/',auth_views.PasswordResetView.as_view(),name='password_reset'),
    path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(),name='password_reset_done'),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    path('reset/done/',auth_views.PasswordResetCompleteView.as_view(),name='password_reset_complete'),
]


admin.site.site_header = "Omaha Retirement Centre"
admin.site.site_title = "Omaha Retirement Centre Admin"
admin.site.site_index_title = "Welcome to Omaha Retirement Centre"

ORC/forms.py
from django import forms
from .models import Resident,MaintenanceWorker,Orc_Staff,Equipment,MaintenanceWork,Roomallotment,Workorder

class ResidentForm(forms.ModelForm):
    class Meta:
        model = Resident
        fields = ('resident_id', 'user','resident_name', 'resident_occupation', 'resident_emailaddress','resident_marital_status', 'resident_familymember_count','resident_petdetails','resident_contactdetails','resident_startdate', 'resident_enddate')


class MaintenanceWorkerForm(forms.ModelForm):
    class Meta:
        model = MaintenanceWorker
        fields = ('worker_id', 'user', 'maintenanceworker_name', 'worker_emailaddress','worker_address','worker_yearsofexperience','worker_contactdetails','worker_startdate','worker_enddate')


class Orc_StaffForm(forms.ModelForm):
    class Meta:
        model = Orc_Staff
        fields = ('orc_staff_id', 'user','orc_staff_name', 'orc_staff_emailaddress', 'orc_staff_address','orc_staff_yearsofexperience', 'orc_staff_contactdetails','orc_staff_position','orc_staff_startdate','orc_staff_enddate')


class WorkorderForm(forms.ModelForm):
    class Meta:
        model = Workorder
        fields = ('resident_name', 'workorder_id', 'resident_id', 'workorder_Description', 'workorder_category','workorder_priority','property_number', 'workorder_opendate','workorder_duedate','workorder_closedate','is_open')


class EquipmentForm(forms.ModelForm):
    class Meta:
        model = Equipment
        fields = ('equipment_id', 'equipment_serialnumber', 'equipment_name', 'equipment_description','is_available','equipment_cost','equipment_purchasedate')

class MaintenanceWorkForm(forms.ModelForm):
    class Meta:
        model = MaintenanceWork
        fields = ('residentid', 'maintenancework_id','maintenancework_description', 'workorder_id','maintenanceworker_name','property_number','equipment_name','maintenancework_cost','maintenancework_opendate','maintenancework_duedate','is_open','maintenancework_closedate')

class RoomallotmentForm(forms.ModelForm):
    class Meta:
        model = Roomallotment
        fields = ('allotment_id', 'resident_name', 'property_number', 'property_floor','allotment_startdate','allotment_enddate')

ORC/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import redirect
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from .forms import *
from .models import *

from django.shortcuts import render, get_object_or_404
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login, authenticate
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm

import datetime
import xlwt
import csv

from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from .serializers import *


def home(request):
    return render(request, 'ORC/home.html',
                  {'ORC': home})


def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('ORC:home')
    else:
        form = UserCreationForm()
    return render(request, 'registration/signup.html', {'form': form})



def about(request):
    return render(request, 'ORC/AboutUs.html')


@login_required
def export_workorders_excel(request):
    response = HttpResponse(content_type='application/ms-excel')
    response['Content-Disposition'] = 'attachment;' \
                                      'filename=workorders.csv'
    wb = xlwt.Workbook(encoding='utf-8')
    ws = wb.add_sheet('Workorders')

    row_num = 0

    font_style = xlwt.XFStyle()
    font_style.font.bold = True

    columns = ['resident', 'id', 'description', 'category', 'priority', 'property number', 'opened date', 'due date', 'closed date', 'open']
    for col_num in range(len(columns)):
        ws.write(row_num, col_num, columns[col_num], font_style)

    font_style.font.bold = False

    workorders = Workorder.objects.all().values_list('resident_name', 'workorder_id', 'workorder_Description', 'workorder_category', 'workorder_priority', 'property_number', 'workorder_opendate', 'workorder_duedate', 'workorder_closedate', 'is_open')

    for wo in workorders:
        row_num += 1
        for col_num in range(len(wo)):
            value = wo[col_num]
            if isinstance(value, datetime.datetime):
                value = value.strftime('%d/%m/%Y')
            if isinstance(value, Resident):
                value = value.__str__()
            if isinstance(value, Roomallotment):
                value = value.__str__()
            ws.write(row_num, col_num, value, font_style)

    wb.save(response)
    return response


@login_required
def workorder_list(request): #resident_id):
        workorder = Workorder.objects.filter()
        return render(request, 'ORC/workorder_list.html', {'workorder': workorder})
    #if request.user.is_resident:
     #   workorder = get_object_or_404(Workorder, pk=workorder.pk)
      #  return redirect(request, 'ORC/workorder_list.html', {'workorder': workorder})


@login_required
def workorder_new(request):
    if request.method == "POST":
        form = WorkorderForm(request.POST)
        if form.is_valid():
            newworkorder = form.save(commit=False)
            newworkorder.created_date = timezone.now()
            newworkorder.save()
            workorder = Workorder.objects.filter(created_date__lte=timezone.now())
            return render(request, 'ORC/workorder_list.html',
                          {'workorder': workorder})
            #return HttpResponseRedirect(reverse('ORC:workorder_list'))
    else:
        form = WorkorderForm()
    # print("Else")
    return render(request, 'ORC/workorder_new.html', {'form': form})


@login_required
def property_list(request):
    roomallotment = Roomallotment.objects.filter(created_date__lte=timezone.now())
    return render(request, 'ORC/property_list.html',
                 {'roomallotments': roomallotment})

@login_required
def property_new(request):
   if request.method == "POST":
       form = RoomallotmentForm(request.POST)
       if form.is_valid():
           newroomallotment = form.save(commit=False)
           newroomallotment.created_date = timezone.now()
           newroomallotment.save()
           roomallotment = Roomallotment.objects.filter(created_date__lte=timezone.now())
           return render(request, 'ORC/property_list.html',
                         {'roomallotments': roomallotment})
   else:
       form = RoomallotmentForm()
       # print("Else")
   return render(request, 'ORC/property_new.html', {'form': form})

@login_required
def property_edit(request, pk):
   roomallotment = get_object_or_404(Roomallotment, pk=pk)
   if request.method == "POST":
       # update
       form = RoomallotmentForm(request.POST, instance=roomallotment)
       if form.is_valid():
           editroomallotment = form.save(commit=False)
           editroomallotment.updated_date = timezone.now()
           editroomallotment.save()
           roomallotment = Roomallotment.objects.filter(created_date__lte=timezone.now())
           return render(request, 'ORC/property_list.html',
                         {'roomallotments': roomallotment})
   else:
        # edit
       form = RoomallotmentForm(instance=roomallotment)
   return render(request, 'ORC/property_edit.html', {'form': form})

@login_required
def property_delete(request, pk):
   roomallotment = get_object_or_404(Roomallotment, pk=pk)
   roomallotment.delete()
   return redirect('ORC:property_list')

@login_required
def maintenancework_list(request):
    maintenancework = MaintenanceWork.objects.filter(created_date__lte=timezone.now())
    return render(request, 'ORC/maintenancework_list.html',
                  {'maintenanceworks': maintenancework})
@login_required
def maintenancework_new(request):
   if request.method == "POST":
       form = MaintenanceWorkForm(request.POST)
       if form.is_valid():
           maintenancework = form.save(commit=False)
           maintenancework.created_date = timezone.now()
           maintenancework.save()
           ##maintenanceworks = MaintenanceWork.objects.filter(created_date__lte=timezone.now())
           return HttpResponseRedirect(reverse('ORC:maintenancework_list'))

   else:
       form = MaintenanceWorkForm()
       print(form)
       # print("Else")
       return render(request, 'ORC/maintenancework_new.html', {'form': form})

@login_required
def maintenancework_edit(request, pk):
   maintenancework = get_object_or_404(MaintenanceWork, pk=pk)
   if request.method == "POST":
       form = MaintenanceWorkForm(request.POST, instance=maintenancework)
       if form.is_valid():
           maintenancework = form.save()
           maintenancework.updated_date = timezone.now()
           maintenancework.save()
           maintenancework = MaintenanceWork.objects.filter(created_date__lte=timezone.now())
           return render(request, 'ORC/maintenancework_list.html', {'maintenanceworks': maintenancework})
   else:
       # print("else")
       form = MaintenanceWorkForm(instance=maintenancework)
   return render(request, 'ORC/maintenancework_edit.html', {'form': form})


@login_required
def maintenancework_delete(request, pk):
   maintenancework = get_object_or_404(MaintenanceWork, pk=pk)
   maintenancework.delete()
   return redirect('ORC:maintenancework_list')

@login_required()
def maintenancework_workerview(request, pk):
    print(" pk of logged in user",pk)
    worker=MaintenanceWorker.objects.get(user_id = pk)
    print(" object",worker)
    workerid=worker.worker_id
    print("worker id ",workerid)
    workerview = [x for x in (MaintenanceWork.objects.filter(maintenanceworker_name_id=workerid))]
    print("workder assigned to worker",workerview)
    return render(request, 'ORC/maintenancework_workerview.html',
                  {'workerview': workerview})


@login_required()
def resident_list(request):
    resident = Resident.objects.filter(created_date__lte=timezone.now())
    return render(request, 'ORC/resident_list.html',
                 {'residents': resident})

@login_required
def resident_new(request):
   if request.method == "POST":
       form = ResidentForm(request.POST)
       if form.is_valid():
           newresident = form.save(commit=False)
           newresident.created_date = timezone.now()
           newresident.save()
           resident = Resident.objects.filter(created_date__lte=timezone.now())
           return render(request, 'ORC/resident_list.html',
                         {'resident': resident})
   else:
       form = ResidentForm()
       # print("Else")
   return render(request, 'ORC/resident_new.html', {'form': form})

@login_required
def resident_edit(request, pk):
   resident = get_object_or_404(Resident, pk=pk)
   if request.method == "POST":
       # update
       form = ResidentForm(request.POST, instance=resident)
       if form.is_valid():
           editresident = form.save(commit=False)
           editresident.updated_date = timezone.now()
           editresident.save()
           resident = Resident.objects.filter(created_date__lte=timezone.now())
           return render(request, 'ORC/resident_list.html',
                         {'residents': resident})
   else:
        # edit
       form = ResidentForm(instance=resident)
   return render(request, 'ORC/resident_edit.html', {'form': form})

@login_required
def resident_delete(request, pk):
   resident = get_object_or_404(Resident, pk=pk)
   resident.delete()
   return redirect('ORC:resident_list')

@login_required()
def resident_workorderview(request, pk):
    print(" pk of logged in user",pk)
    Res=Resident.objects.get(user_id = pk)
    print(" object",Resident)
    res_id=Res.resident_id

ORC/templates/ORC/equipment_edit.html
{% extends 'ORC/base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div class="row"  align="center">
    <form method="POST" class="customer-form" > {% csrf_token %}
        {{ form|crispy }}<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
        <button type="submit" class="save btn btn-primary" >Update</button><br>
    </form></div>
{% endblock %}

ORC/templates/ORC/equipment_list.html
{% extends 'ORC/base.html' %}
   {% block content %}




        <h2  style="color:firebrick" align="center" ><b>EQUIPMENT DETAILS</b></h2>
    <br>

        <table class="table-bordered" style="background-color:white" align="center">
            <thead>
                        <tr class="bg-info" style="background:white">
                <th>Equipment Id</th>
                <th>Equipment Serial Number</th>
                <th>Equipment Name</th>
                <th>Equipment Description</th>
                <th>Equipment Availability</th>
                <th>Equipment Cost</th>
                <th>Equipment Purchase Date</th>




                <th colspan="6" >Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for equipment in equipments %}
                <tr>

                    <td>{{ equipment.equipment_id }}</td>
                    <td>{{ equipment.equipment_serialnumber }}</td>
                    <td>{{ equipment.equipment_name }}</td>
                    <td>{{ equipment.equipment_description }}</td>
                    <td>{{ equipment.is_available }}</td>
                    <td>{{ equipment.equipment_cost }}</td>
                    <td>{{ equipment.equipment_purchasedate }}</td>


{% if user.is_maintenanceworker %}
 <td><a href=""
                  class="btn btn-danger">Access Denied</a>
    {% else  %}
                        <td><a href="{% url 'ORC:equipment_edit' pk=equipment.pk%}" class="btn btn-warning">Edit</a>


<td><a href="{% url 'ORC:equipment_delete' pk=equipment.pk%}" onclick="return confirm ('Are you sure you want to delete?')"
                  class="btn btn-danger">Delete</a>
{% endif %}
                </tr>

            {% endfor %}

            </tbody>

        </table>
        </table>
       <br>

       {% if user.is_maintenanceworker %}
        <td><a href=""
                  class="btn btn-danger">Access Denied</a>
          {% else  %}
 <td><a href="{% url 'ORC:equipment_new' %}"
                           class="btn btn-primary">Add New Equipment</a>
{% endif %}
    </body>
    </html>
{% endblock %}

ORC/templates/ORC/maintenance_worker_list.html
{% extends 'ORC/base.html' %}
   {% block content %}



        <h2  style="color:firebrick" align="center" ><b>Maintenance Worker Details</b></h2>
    <br>

        <table class="table-bordered" style="background-color:white"  align="center">
            <thead>
                        <tr class="bg-info" style="background:white">
                <th>Maintenance Worker Id</th>
                <th>User Name</th>
                <th>Maintenance Worker Name</th>
                <th>Maintenance Worker Email Address</th>
                <th>Maintenance Worker Address</th>
                <th>Maintenance Worker Years Of Experience</th>
                <th>Maintenance Worker Contact Details</th>
                <th>Maintenance Worker Start Date</th>
                <th>Maintenance Worker End Date</th>




                <th colspan="9" >Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for maintenanceworker in maintenanceworkers %}
                <tr>

                    <td>{{ maintenanceworker.worker_id}}</td>
                    <td>{{ maintenanceworker.user}}</td>
                    <td>{{ maintenanceworker.maintenanceworker_name }}</td>
                    <td>{{ maintenanceworker.worker_emailaddress }}</td>
                    <td>{{ maintenanceworker.worker_address }}</td>
                    <td>{{ maintenanceworker.worker_yearsofexperience }}</td>
                    <td>{{ maintenanceworker.worker_contactdetails }}</td>
                    <td>{{ maintenanceworker.worker_startdate }}</td>
                    <td>{{ maintenanceworker.worker_enddate }}</td>


                        <td><a href="{% url 'ORC:maintenance_worker_edit' pk=maintenanceworker.pk%}" class="btn btn-warning">Edit</a>


<td><a href="{% url 'ORC:maintenance_worker_delete' pk=maintenanceworker.pk%}" onclick="return confirm ('Are you sure you want to delete?')"
                  class="btn btn-danger">Delete</a>

                </tr>

            {% endfor %}

            </tbody>

        </table>
        </table>
       <br>
 <td><a href="{% url 'ORC:maintenance_worker_new' %}"
                           class="btn btn-primary">Add New Maintenance Worker</a>
    </body>
    </html>
{% endblock %}

ORC/templates/ORC/maintenance_worker_new.html
{% extends 'ORC/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <h1>Add New Maintenance Worker</h1>
    <form method="POST" class="service-form">{% csrf_token %}
          {{ form|crispy }}<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
        <button type="submit" class="save btn btn-primary">Save</button>
    </form>
{% endblock %}

ORC/templates/ORC/orc_staff_list.html
{% extends 'ORC/base.html' %}
   {% block content %}


        <h2  style="color:firebrick" align="center" ><b>STAFF DETAILS</b></h2>
<br>

        <table class="table-bordered" style="background-color:white" align="center">
            <thead>
                        <tr class="bg-info" style="background:white">
                <th>Staff Id</th>
                <th>User</th>
                <th>Staff Name</th>
                <th>Staff Email Address </th>
                <th>Staff Address </th>
                <th>Staff Years Of Experience</th>
                <th>Staff Contact Details</th>
                <th>Staff Position</th>
                <th>Staff Start Date</th>
                <th>Staff End Date</th>




                <th colspan="9" >Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for orc_staff in orc_staffs %}
                <tr>

                    <td>{{ orc_staff.orc_staff_id }}</td>
                    <td>{{ orc_staff.user }}</td>
                    <td>{{ orc_staff.orc_staff_name }}</td>
                    <td>{{ orc_staff.orc_staff_emailaddress }}</td>
                    <td>{{ orc_staff.orc_staff_address }}</td>
                    <td>{{ orc_staff.orc_staff_yearsofexperience }}</td>
                    <td>{{ orc_staff.orc_staff_contactdetails }}</td>
                    <td>{{ orc_staff.orc_staff_position }}</td>
                    <td>{{ orc_staff.orc_staff_startdate }}</td>
                    <td>{{ orc_staff.orc_staff_enddate }}</td>





                        <td><a href="{% url 'ORC:orc_staff_edit' pk=orc_staff.pk%}" class="btn btn-warning">Edit</a>


<td><a href="{% url 'ORC:orc_staff_delete' pk=orc_staff.pk%}" onclick="return confirm ('Are you sure you want to delete?')"
                  class="btn btn-danger">Delete</a>

                </tr>

            {% endfor %}

            </tbody>

        </table>
        </table>
       <br>
 <td><a href="{% url 'ORC:orc_staff_new' %}"
                           class="btn btn-primary">Add New Staff</a>
    </body>
    </html>
{% endblock %}

ORC/templates/ORC/property_list.html
  {% extends 'ORC/base.html' %}
   {% block content %}






        <h2  style="color:firebrick" align="center" ><b>ROOM ALLOTTMENT DETAIL</b></h2>
    <br>

        <table class="table-bordered" style="background-color:white" align="center">
            <thead>
                        <tr class="bg-info" style="background:white">
                <th>Allotment Id</th>
                <th>Resident Name</th>
                <th>Property Number</th>
                <th>Property Floor</th>
                <th>Allotment Start Date</th>
                <th>Allotment End Date</th>




                <th colspan="6" >Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for roomallotment in roomallotments %}
                <tr>

                    <td>{{ roomallotment.allotment_id }}</td>
                    <td>{{ roomallotment.resident_name }}</td>
                    <td>{{ roomallotment.property_number }}</td>
                    <td>{{ roomallotment.property_floor }}</td>
                    <td>{{ roomallotment.allotment_startdate }}</td>
                    <td>{{ roomallotment.allotment_enddate }}</td>





                        <td><a href="{% url 'ORC:property_edit' pk=roomallotment.pk%}" class="btn btn-warning">Edit</a>


<td><a href="{% url 'ORC:property_delete' pk=roomallotment.pk%}" onclick="return confirm ('Are you sure you want to delete?')"
                  class="btn btn-danger">Delete</a>

                </tr>

            {% endfor %}

            </tbody>

        </table>
        </table>
       <br>
 <td><a href="{% url 'ORC:property_new' %}"
                           class="btn btn-primary">Add New Room Allotment</a>
    </body>
    </html>
{% endblock %}

ORC/templates/ORC/workorder_list.html
{% extends 'ORC/base.html' %}
{% block content %}

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">


    <style>
        body,html{
            height: 100%;
            margin: 0;
            background: #7F7FD5;
            background: -webkit-linear-gradient(to right, #ffffff, #ffffff);
            background: linear-gradient(to right, #ffffff, #de9404);
        }
        #events_card{
            padding-bottom: 40px;
        }
    </style>



    <h1 class ="probootsrap-card-heading"> Workorder Details</h1><br>
    <ul class="">
        <a href="{% url 'ORC:workorder_new' %}" style="padding-right: 15Px" class="row"><span class="btn btn-primary">New workorder</span></a>
        {% if request.user.is_orc_staff %}
            <a href="{% url 'ORC:export_workorders_xls' %}" style="padding-right: 15Px; padding-top: 5Px" class="row"><span class="btn btn-primary">Export</span></a>
        {% endif %}
    </ul>

    <div class="content container">

    <div class="row" id="events_card">
        {% for wo in workorder %}
            <div class="col-md-16"></div>
            <div class="col-md-5">
                <div class="card text-white bg-dark mb-3">
                    <div class="card-body">
                         <h5 class="card-title" style = "color:lightblue" >Workorder ID: {{ wo.workorder_id }}</h5>
                            <strong style = "color:yellow">Resident Name::</strong><b class="card-text" style = "color:#f3f7cc">{{ wo.resident_name }}</b><br>
                            <strong style = "color:yellow">Description::  </strong><b class="card-text" style = "color:#f3f7cc">{{ wo.workorder_Description }}</b><br>
                            <strong style = "color:yellow">Priority::      </strong><b class="card-text" style = "color:#f3f7cc">{{ wo.workorder_priority }}</b><br>
                            <strong style = "color:yellow">Room Number::      </strong><b class="card-text" style = "color:#f3f7cc">{{ wo.property_number }}</b><br>
                            <strong style = "color:yellow">Created Date::   </strong><b class="card-text" style = "color:#f3f7cc">{{ wo.created_date }}</b><br>
                        {%  if wo.is_open %}
                            <strong style = "color:yellow">Status::  </strong><b class="badge badge-success">Open</b>
                        {% else %}
                            <strong style = "color:yellow">Status::  </strong><span class="badge badge-danger">Closed</span>
                        {% endif %}
                            <br><br>
                            <td><a href="{% url 'ORC:workorder_delete' pk=wo.pk %}" onclick="return confirm ('Are you sure you want to delete?')"
                                   class="btn btn-danger">Delete</a></td>

                            <td><a href="{% url 'ORC:workorder_edit' pk=wo.pk %}" class="btn btn-warning">Edit</a></td>

                    </div>
                </div>
            </div>

        {% endfor %}
    </div>
  </div>

{% endblock %}